# Generated by Django 6.0.3 on 2026-03-15 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_pybehaviorlog_v6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observationevent',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='multi_events', to='tracker.subject'),
        ),
        migrations.AddField(
            model_name='observationsession',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationsession',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observationsession',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationsession',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cowlog_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observationsession',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('validated', 'Validated'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='independentvariabledefinition',
            name='set_values',
            field=models.TextField(blank=True, help_text='Comma-separated values for list fields.'),
        ),
        migrations.AlterField(
            model_name='independentvariabledefinition',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('longtext', 'Long text'), ('numeric', 'Numeric'), ('set', 'Value from a list'), ('boolean', 'Boolean'), ('timestamp', 'Timestamp')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='observationsession',
            name='session_kind',
            field=models.CharField(choices=[('media', 'Media'), ('live', 'Live')], default='media', max_length=10),
        ),
        migrations.CreateModel(
            name='ObservationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('event', 'Event'), ('annotation', 'Annotation'), ('session', 'Session'), ('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status', 'Status change'), ('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cowlog_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tracker.observationsession')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ObservationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_session_kind', models.CharField(default='media', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('behaviors', models.ManyToManyField(blank=True, related_name='templates', to='tracker.behavior')),
                ('modifiers', models.ManyToManyField(blank=True, related_name='templates', to='tracker.modifier')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_templates', to='tracker.project')),
                ('subjects', models.ManyToManyField(blank=True, related_name='templates', to='tracker.subject')),
                ('variable_definitions', models.ManyToManyField(blank=True, related_name='templates', to='tracker.independentvariabledefinition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='observationsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracker.observationtemplate'),
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='tracker.project')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='tracker.subjectgroup'),
        ),
        migrations.AddConstraint(
            model_name='observationtemplate',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_template_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='subjectgroup',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_subject_group_name_per_project'),
        ),
    ]
